- build.gradle
- src/main/java/com/vitacheck/config/SecurityConfig.java
- src/main/java/com/vitacheck/config/SwaggerConfig.java
Close #9 
swagger 기본설정
기본설정만 하였습니다
추가하고 싶으신거 말해주시면 수정할게요!
> feat(#9):Swagger 기본 설정

- src/main/java/com/vitacheck/controller/PurposeController.java
- src/main/java/com/vitacheck/domain/purposes/AllPurpose.java
- src/main/java/com/vitacheck/dto/AllPurposeDto.java
- src/main/java/com/vitacheck/service/PurposeService.java
Close #
Figma 상 기획된 모든 목적 카테고리를 ENUM으로 정의했고, 이걸 모두 반환하는 API를 설계했습니다
endpoint: /api/v1/purposes
- Purpose 관련 ENUM 클래스, Service, Controller 파일 추가하였습니다.
> feat(#21): 모든 목적 ENUM 정의 및 모든 목적 반환 GET API 설계

- src/main/resources/application-local.yml.example
- src/main/resources/application.yml
> feat: 테스트용 application.yml 파일 추가

- src/main/java/com/vitacheck/controller/CombinationController.java
- src/main/java/com/vitacheck/domain/Combination/Combination.java
- src/main/java/com/vitacheck/domain/Combination/RecommandType.java
- src/main/java/com/vitacheck/dto/CombinationDTO.java
- src/main/java/com/vitacheck/repository/CombinationRepository.java
- src/main/java/com/vitacheck/service/CombinationService.java
조합 분석 내부 로직 제외하고 API 작성 하였습니다
Close #25 
주의가 필요한 조합 / 궁합이 좋은 조합 은 pm님과 상의 후 특정 값을 db에 넣어서 고정된 값을 보여주는것으로 하기로 하였습니다.
분석 로직은 어떤 정보를 받아서 어떻게 분석할지 아직 확실치 않은것 같아 상의 후 개발하겠습니다.(우선 더미데이터가 나오게 해두었습니다)
스웨거를 더 자세히 작성해야 할 것 같으면 말해주세요!
> feat(#25):조합 API 기본 구조 작성

- src/main/java/com/vitacheck/controller/PurposeController.java
Close #29 
GET Purposes API의 swagger 설명을 추가하였습니다
> refactor(#29): GET Purposes API swagger 설명 보강

- .gitignore
- build.gradle
- src/main/java/com/vitacheck/config/AwsS3Config.java
- src/main/java/com/vitacheck/dto/OAuthAttributes.java
- src/main/java/com/vitacheck/global/apiPayload/code/ErrorCode.java
- src/main/java/com/vitacheck/service/S3UploadService.java
- src/main/resources/application-prod.yml
- src/test/java/com/vitacheck/VitacheckBeApplicationTests.java
- src/test/resources/application-test.yml
Close #42
VitaCheck 백엔드 애플리케이션을 실제 운영 환경에 배포하기 위한 **AWS 클라우드 인프라 구축 및 관련 애플리케이션 설정을 완료**했습니다.
이 PR이 머지되면, 우리 프로젝트는 안정적인 클라우드 데이터베이스(RDS), 이미지 저장소(S3), 애플리케이션 서버(EC2) 환경에서 동작할 수 있는 기반을 갖추게 됩니다.
- **RDS**: MySQL 데이터베이스 인스턴스 생성 및 보안 그룹 설정
- **S3**: 이미지 등 정적 파일 저장용 버킷 생성 및 퍼블릭 액세스 설정
- **IAM**: EC2가 RDS와 S3에 접근할 수 있는 권한을 가진 IAM 사용자 생성 및 Access Key 발급
*(위 인프라 구축은 AWS 콘솔에서 직접 진행했으며, 이 PR은 해당 인프라와 연동하기 위한 코드 변경사항을 포함합니다.)*
- **`build.gradle`**: AWS SDK(`spring-cloud-starter-aws`) 의존성을 추가했습니다.
- **`application-prod.yml`**: 운영(`production`) 환경을 위한 프로파일을 새로 추가했습니다.
- RDS 및 S3 접속 정보를 **환경 변수**(`${...}`)로 참조하도록 설정하여, 민감 정보가 코드에 노출되지 않도록 했습니다.
- `spring.jpa.hibernate.ddl-auto` 옵션을 `none`으로 설정하여 운영 DB의 스키마를 안전하게 보호합니다.
- **`S3UploadService.java`**: 이미지 파일을 S3에 업로드하는 서비스 로직을 구현했습니다.
- …
> feature(#42): AWS 세팅

- src/main/java/com/vitacheck/config/FirebaseConfig.java
- src/test/java/com/vitacheck/VitacheckBeApplicationTests.java
This reverts commit 7323e367537897aaadad63194bb3541992b8a66d.
> Revert "fix: ci/cd 버그 수정"

- src/main/java/com/vitacheck/domain/Ingredient.java
- src/main/java/com/vitacheck/dto/CombinationDTO.java
- src/main/java/com/vitacheck/service/CombinationService.java
Close #
combination관련 충돌 해결
일단 도메인에 recommenededDosage 추가하는 방식으로 오류 해결하였습니다. 추후에 논의 후 더 나은 방향으로 수정하겠습니다.
> fix:combination 관련 충돌 해결

- src/main/java/com/vitacheck/config/SecurityConfig.java
Close #108 
cors 설정 localhost:5173으로 변경
> fix(#108): cors 설정 변경

- src/main/java/com/vitacheck/domain/AlternativeFood.java
- src/main/java/com/vitacheck/domain/Ingredient.java
- src/main/java/com/vitacheck/domain/mapping/IngredientAlternativeFood.java
Close #110 
1) lower_limit 삭제 
2) recommended_ → recommended_dosage로 수정 (아래 스크린샷 참고)
여기 수정했습니다.
> [REFRACTOR] Ingredient 관련 엔티티 수정

- src/main/resources/application-prod.yml
related to #136 
ec2에서 스프링을 재실행시켜, RDS 테이블 생성을 다시함 (최신 엔티티로 갱신)
> [REFRACTOR] RDS 테이블 재생성 위한 application-prod 수정

- src/main/java/com/vitacheck/controller/SupplementController.java
- src/main/java/com/vitacheck/dto/SupplementDto.java
- src/main/java/com/vitacheck/repository/IngredientDosageRepository.java
- src/main/java/com/vitacheck/repository/SupplementRepository.java
- src/main/java/com/vitacheck/service/SupplementService.java
Close #153 
특정 영양제의 상세 정보를 반환하는 API 입니다
- id, 이름
- 성분 함량
- 성분 함량이 미달, 적정, 초과 중 어디인지
- 눈금으로 표현하기 위한 퍼센테이지 환산값은 얼마인지
이러한 정보를 반환합니다
> [FEAT] 특정 영양제 상세 성분 조회 API 제작

- src/main/java/com/vitacheck/config/SecurityConfig.java
Close #164
SecurityConfig에 알림발송 API 링크 허용
> fix(#164): SecurityConfig 허용 경로 추가

- src/main/java/com/vitacheck/config/oAuth/OAuth2SuccessHandler.java
localhost:3000 -> localhost:5173으로 변경
> docs: localhost:3000 -> localhost:5173

- src/main/resources/application-prod.yml
엔티티 구축 다시 한 후, 서버 rds에 변경된 엔티티 create
related to #178
> CI/CD DB 엔티티 재생성(create)

- src/main/resources/application-prod.yml
Close #
엔티티 구조 수정 후, 서버에 다시 db 생성하고 나서 ddl 설정 none으로 다시 변경함
> docs:CI/CD ddl 설정 변경 (none)

- src/main/java/com/vitacheck/controller/SupplementController.java
- src/main/java/com/vitacheck/controller/UserController.java
- src/main/java/com/vitacheck/domain/user/User.java
- src/main/java/com/vitacheck/dto/UserDto.java
- src/main/java/com/vitacheck/repository/SupplementRepositoryCustom.java
- src/main/java/com/vitacheck/repository/SupplementRepositoryImpl.java
- src/main/java/com/vitacheck/service/SearchLogService.java
- src/main/java/com/vitacheck/service/SupplementService.java
- src/main/java/com/vitacheck/service/UserService.java
> feat(#172): 검색결과 정렬

- src/main/resources/application-prod.yml
Close #
Redis 설정 application-prod.yml에 추가
> Ci Cd에 redis 추가(application-prod.yml 수정)

- src/main/java/com/vitacheck/config/SecurityConfig.java
- src/main/java/com/vitacheck/controller/SearchController.java
Close #216 
실시간 인기 검색어 최대 10개 조회한다.
redis에서 검색 수 많은 순으로 정렬되어 조회
> feat(#216): 인기 검색어 조회

- src/main/java/com/vitacheck/controller/CombinationController.java
- src/main/java/com/vitacheck/controller/SearchController.java
- src/main/java/com/vitacheck/repository/SearchLogRepository.java
- src/main/java/com/vitacheck/repository/SupplementRepository.java
- src/main/java/com/vitacheck/service/CombinationService.java
- src/main/java/com/vitacheck/service/DosageService.java
- src/main/java/com/vitacheck/service/SearchLogService.java
Close #238 
최근 검색어 / 최근 본 상품 api 개발
> feat(#238):최근 검색어 / 최근 본 상품 api 개발

- src/main/java/com/vitacheck/config/oAuth/OAuth2SuccessHandler.java
- src/main/resources/application-prod.yml
> fix: 네이버 로그인 URI 수정

- src/main/java/com/vitacheck/service/SupplementService.java
Close #283 
영양제 상세 정보에서 normalized 값이 항상 0으로 계산되고 있었습니다. 계산 로직을 수정하였습니다.
또한 기존의 비율 환산 단위가 변경된 Figma UI에 적용하기 어려운 점이 있어, UI 구성이 쉽도록 반환 기준으로 좀 더 정제하였습니다.
```
"visualization": {
"normalizedAmountPercent": 10.0, // 실제 영양소 함량은 amount를 퍼센테이지로 환산한 결과
"recommendedStartPercent": 30.0, // 권장 섭취량을 퍼센테이지로 환산한 결과 
"recommendedEndPercent": 100.0 // 최대 섭취량을 퍼센테이지로 환산한 결과 (따라서 항상 100%)
}
```
UI 구성하실 때,  전체 눈금의 길이는 0~150으로 두시고 (150인 이유는, 최대 섭취량을 조금 또는 훌쩍 뛰어넘는 영양성분이 있을 경우를 대비)
recommendedStartPercent(30) ~ recommendedEndPercent(100) 구간을 기준으로 normalizedAmountPercent(10) 을 띄우시면 됩니다.
> fix(#283): 영양제 상세정보 중 함량 계산에서 잘못된 로직 수정 + UI 구성 쉽도록 계산 기준을 수정

- build.gradle
- src/main/java/com/vitacheck/config/SecurityConfig.java
- src/main/java/com/vitacheck/controller/OcrProxyController.java
- src/main/java/com/vitacheck/dto/OcrRequest.java
- src/main/java/com/vitacheck/service/OcrProxyService.java
- src/main/resources/application-prod.yml
- ncloud ocr 의존성 추가
- OcrProxyService & OcrProxyController 추가
- dto 추가
> feat: ncloud Ocr 관련 설정들 추가

- src/main/java/com/vitacheck/controller/IngredientController.java
> 인기성분 api 주소 변경

- module-auth/src/main/java/com/vitacheck/auth/config/SecurityConfig.java
- module-common/src/main/java/com/vitacheck/common/config/RestTemplateConfig.java
- SecurityConfig에 경로 /swagger-ui.html 추가
- RestTemplateConfig를 module-common/config로 이동
문제 생길시 롤백 필요
> hotfix: SecurityConfig에 Swagger 설정 추가 및 RestTemplateConfig 위치 수정

- build.gradle
- module-auth/build.gradle
- module-product/build.gradle
- module-user/build.gradle
- 메인 모듈 build.gradle에 자바 버전 17로 고정
- 다른 모듈에서 자바 버전 세팅 코드 삭제
> fix: build.gradle에 자바 버전 17로 고정

- module-product/src/main/java/com/vitacheck/product/controller/IngredientController.java
Close #
성분 api 에서 appi/v1이 두번 매핑되어 오류가 발생함. 이를 수정한 pr이다.
수정 전
수정 후
> fixed : 오류로 인한 성분 api url 수정

- src/main/resources/application-prod.yml
> [CHORE] 데이터베이스 재구성 (application-prod) 수정

- module-auth/src/main/java/com/vitacheck/auth/config/SecurityConfig.java
- module-product/src/main/java/com/vitacheck/product/domain/Supplement/Brand.java
- module-product/src/main/java/com/vitacheck/product/domain/Supplement/Supplement.java
- module-product/src/main/java/com/vitacheck/product/service/IngredientService.java
- module-product/src/main/java/com/vitacheck/product/service/SupplementService.java
Close #359 
filter 변경해서 인증 없이 허용할 수 있는 엔드포인트 설정 및 필터 로직 변경
SecurityConfig 수정이 있습니다. 검토 후 머지해주세요
> fix(#359): 인증 없이 성분 및 영양제 상세 조회 가능하게 변경

- src/main/java/com/vitacheck/Activity/controller/SearchLogController.java
> refactor : searchLog api url 수정
