build.gradle, src/main/java/com/vitacheck/config/CustomAuthenticationEntryPoint.java, src/main/java/com/vitacheck/config/SecurityConfig.java, src/main/java/com/vitacheck/config/jwt/JwtAuthenticationFilter.java, src/main/java/com/vitacheck/config/jwt/JwtUtil.java, src/main/java/com/vitacheck/controller/UserController.java
Close #12 
Springdoc OpenAPI 어노테이션을 사용하여 `UserController`에 있는 사용자 관련 API(내 정보 조회/수정)의 명세를 작성했습니다.
이를 통해 프론트엔드 개발자 및 다른 팀원들이 Swagger UI에서 API의 기능, 요청/응답 형식 등을 명확히 확인하고 직접 테스트까지 해볼 수 있게 되었습니다.
API 명세에 작성된 설명(`summary`, `description`)이 다른 팀원들이 보기에 명확하고 충분한지 검토 부탁드립니다.
혹시 더 추가되거나 수정되면 좋을 내용이 있다면 편하게 코멘트 남겨주세요!
=> docs(#12): UserController에 Swagger 문서화 추가

.gitignore, build.gradle, src/main/java/com/vitacheck/controller/LikeRestController.java, src/main/java/com/vitacheck/domain/Brand.java, src/main/java/com/vitacheck/domain/Like.java, src/main/java/com/vitacheck/domain/Supplement.java, src/main/java/com/vitacheck/dto/LikeToggleResponseDto.java, src/main/java/com/vitacheck/repository/LikeRepository.java, src/main/java/com/vitacheck/repository/SupplementRepository.java, src/main/java/com/vitacheck/service/LikeCommandService.java, src/main/java/com/vitacheck/service/UserService.java
Close #36 
JWT 토큰 기반 인증 및 토글 방식 찜하기 기능 구현 확인 부탁드립니다.
예외 처리 및 응답 포맷 관련 피드백도 환영합니다.
=> feat(#36): 영양제 찜하기 API 설계

src/main/java/com/vitacheck/controller/LikeRestController.java, src/main/java/com/vitacheck/dto/LikedSupplementResponseDto.java, src/main/java/com/vitacheck/repository/LikeRepository.java, src/main/java/com/vitacheck/service/LikeQueryService.java
Close #46 
내가 찜한 영양제 목록 조회 API 구현
LikeRestController 추가 로직 구현
LikeCommandService 추가 로직 구현
LikesRepository 추가 로직 구현
LikeQueryService 새로 생성
Swagger 태그 설정 (@Tag 추가)
Jwt 인증 연동 (로그인 사용자 기반 조회)
=> feat(#46): 내가 찜한 영양제 목록 조회 API 설계

src/main/java/com/vitacheck/controller/LikeController.java, src/main/java/com/vitacheck/controller/NotificationRoutineController.java, src/main/java/com/vitacheck/domain/NotificationRoutine.java, src/main/java/com/vitacheck/domain/RoutineDay.java, src/main/java/com/vitacheck/domain/RoutineDayOfWeek.java, src/main/java/com/vitacheck/domain/RoutineTime.java, src/main/java/com/vitacheck/dto/RoutineRegisterRequestDto.java, src/main/java/com/vitacheck/dto/RoutineRegisterResponseDto.java, src/main/java/com/vitacheck/global/apiPayload/code/ErrorCode.java, src/main/java/com/vitacheck/repository/NotificationRoutineRepository.java, src/main/java/com/vitacheck/repository/RoutineDayRepository.java, src/main/java/com/vitacheck/repository/RoutineTimeRepository.java, src/main/java/com/vitacheck/service/NotificationRoutineCommandService.java
Close #48 
내 영양제 복용 루틴 등록 기능 구현
중복 루틴 등록 방지 로직 추가 (userId + supplementId + 요일 + 시간 기준)
DTO, Entity, Service, Repository, Controller 계층 개발 완료
Swagger 테스트용 예시 및 CustomException 처리 적용
복용 루틴 중복 에러코드 추가 완료
=> feat(#48): 내 영양제 복용 루틴 등록 API 설계

src/main/java/com/vitacheck/controller/NotificationRoutineController.java, src/main/java/com/vitacheck/dto/RoutineResponseDto.java, src/main/java/com/vitacheck/repository/NotificationRoutineRepository.java, src/main/java/com/vitacheck/service/RoutineQueryService.java
Close #51 
내 복용 루틴 목록 조회 API (`GET /api/v1/notifications/routines`) 구현
`RoutineResponseDto` 생성 (루틴 ID, 영양제 정보, 요일/시간 리스트 포함)
`NotificationRoutineController`에 조회용 API 추가
`RoutineQueryService`에서 stream 기반 DTO 변환
`NotificationRoutineRepository.findAllByUserId(Long userId)` 메서드 추가
Swagger 문서 설명 및 예외 코드 정리
=> feat(#51): 내 복용 루틴 목록 조회 API 설계

build.gradle, src/main/java/com/vitacheck/config/FirebaseConfig.java, src/main/java/com/vitacheck/domain/Brand.java, src/main/java/com/vitacheck/domain/Supplement.java, src/main/java/com/vitacheck/global/apiPayload/code/ErrorCode.java, src/main/resources/application-prod.yml
Close #79 
CI/CD 배포 시 firebase-service-account-key.json 파일을 찾지 못해 서버가 구동되지 않는 문제를 해결했습니다.
IntelliJ와 Gradle의 빌드 불일치로 인해 리소스 파일이 누락되는 현상이 근본 원인이었으며, 이를 해결하기 위해 빌드 및 실행 환경을 Gradle 기준으로 표준화했습니다. 또한, 운영 환경의 FCM 키 관리를 위해 AWS Secrets Manager를 도입하여 보안을 강화하고 로컬 개발 환경 설정을 분리했습니다.
[x] IntelliJ 빌드 환경 표준화
모든 빌드 및 실행 작업을 IntelliJ IDEA가 아닌 Gradle에 위임하도록 설정을 변경했습니다.
build.gradle에 sourceSets 및 clean task를 추가하여 QueryDSL Q-File 생성 오류 및 리소스 누락 문제를 해결했습니다.
[x] Firebase 키 관리 방식 변경
운영 환경: AWS Secrets Manager를 사용하도록 spring-cloud-starter-aws-secrets-manager-config 의존성을 추가하고, application-prod.yml에 관련 설정을 추가했습니다.
로컬 환경: application-local.yml을 신규 생성하여 로컬 전용 설정을 분리하고, 프로젝트 최상위 경로에서 firebase-service-account-key.json 파일을 직접 읽도록 수정했습니다.
[x] Lombok @Builder 경고 수정
Supplement, Brand 엔티티의 List 필드에 @Builder.Default를 추가하여 빌드 …
=> Fix(#79): 빌드 환경 표준화 및 FCM 키 관리 개선으로 배포 실패 문제 해결

src/main/java/com/vitacheck/config/jwt/JwtAuthenticationFilter.java
Close #114 
JWT 인증 필터에서 `@AuthenticationPrincipal`이 null로 들어오는 버그 수정
JwtAuthenticationFilter`에서 `UsernamePasswordAuthenticationToken`의 Principal을 `User` → `CustomUserDetails`로 수정
인증된 사용자 정보가 SecurityContext에 정상적으로 등록되도록 처리
Swagger 테스트 시 500 에러 발생 문제 해결
이번 수정으로 Swagger 및 클라이언트에서 JWT 인증 기반 요청 시  
정상적으로 유저 정보가 주입되도록 개선했습니다.
=> fix(#114): JwtAuthenticationFilter 클래스 인증 오류 수정

src/main/java/com/vitacheck/controller/SupplementController.java, src/main/java/com/vitacheck/domain/Brand.java, src/main/java/com/vitacheck/dto/SupplementDetailResponseDto.java, src/main/java/com/vitacheck/repository/LikeRepository.java, src/main/java/com/vitacheck/repository/SupplementRepository.java, src/main/java/com/vitacheck/service/SupplementService.java
Close #125 
특정 영양제의 상세 정보를 반환하는 API를 만들었습니다.
영양제 id를 query parameter로 받아 상세정보를 조회하여 Figma 상세화면과 같은 형태로 제공합니다
(영양제 상세성분, 특정 브랜드의 모든 영양제는 별도 API로 분리하였기 때문에 이 API에는 데이터가 없습니다)
=> [FEAT] 특정 영양제 상세 정보 반환 API 제작

src/main/java/com/vitacheck/controller/LikeController.java, src/main/java/com/vitacheck/dto/LikedIngredientResponseDto.java, src/main/java/com/vitacheck/repository/IngredientLikeRepository.java, src/main/java/com/vitacheck/service/IngredientLikeQueryService.java
Close #135 
GET /api/v1/users/me/likes/ingredients API 구현
IngredientLikeQueryService 생성 및 비즈니스 로직 구현
IngredientLikeRepository에 findAllByUserId(Long userId) 메서드 추가
응답 DTO: LikedIngredientResponseDto 생성 (ingredientId, name 포함)
인증 실패 시 401 응답 처리 (userDetails == null 체크)
LikeController에 성분 찜 목록 조회 API 메서드 추가
Swagger 문서화 (@Operation, @ApiResponse 등 적용)
인증 미들웨어 통과하지 못하면 UNAUTHORIZED 응답 처리 추가
리뷰부탁드립니다!
=> feat(#135): 찜한 성분 조회 API 설계 완료

src/main/java/com/vitacheck/controller/SupplementController.java, src/main/java/com/vitacheck/dto/SupplementDto.java, src/main/java/com/vitacheck/repository/SupplementRepository.java, src/main/java/com/vitacheck/service/SupplementService.java
Close #151 
사용자가 어떤 영양제를 볼 때, 하단에 이 영양제를 만든 브랜드의 다른 영영제 목록을 출력하는 컴포넌트 내부 데이터를 반환해주는 API 입니다
=> [FEAT] 특정 브랜드의 다른 영양제 목록 반환 API 제작

src/main/java/com/vitacheck/controller/NotificationRoutineController.java, src/main/java/com/vitacheck/service/RoutineQueryService.java
Close #156 
복용 루틴 조회 API의 isTaken 판단 로직과 날짜 필터 기능 개선
RoutineQueryService에서 isTaken 값을 IntakeRecord.isTaken 기준으로 정확하게 판단하도록 수정
GET /api/v1/notifications/routines?date=YYYY-MM-DD 요청 시, date 파라미터 반영되도록 컨트롤러 및 서비스 수정
테스트를 통해 POST /records/{id}/toggle 후 해당 날짜 기준 isTaken 반영 여부 확인 완료
버그 수정했습니다! 리뷰 부탁드려요!
=> bug(#156): 로직 수정 완료

src/main/java/com/vitacheck/controller/IntakeRecordController.java, src/main/java/com/vitacheck/controller/NotificationRoutineController.java, src/main/java/com/vitacheck/service/IntakeRecordCommandService.java
Close #158 
섭취 여부 토글 API와 복용 루틴 조회 API에 Swagger 명세 보강
날짜 파라미터(date)에 대한 설명 추가
미입력 시 오늘 날짜가 기본값임을 명시
입력 형식은 yyyy-MM-dd 예시 포함
isTaken 필드가 섭취 기록 존재 여부가 아닌 isTaken 실제 값 기준임을 명확히 설명
POST /notifications/records/{id}/toggle → Swagger에 date 파라미터 명세 및 예시 추가
GET /notifications/routines → 날짜 기본값, 형식, isTaken 판단 기준 등 상세 설명 추가
Swagger 문서만 수정한 PR입니다.
프론트 개발자들이 date 파라미터 사용 시 헷갈리지 않도록 명확히 문서화했습니다.
기능 로직에는 영향 없습니다! 🙇🏻‍♂️
=> feat(#158): 로직 수정 완료

src/main/java/com/vitacheck/controller/NotificationSettingsController.java, src/main/java/com/vitacheck/service/UserService.java
Close #160 
알림 설정 기능의 안정성을 높이고 API 문서의 명확성을 개선했습니다. 회원가입 및 로그인 시점에 기본 알림 설정을 자동으로 생성하여 데이터 누락으로 인한 오류를 방지하고, Swagger API 문서의 요청 예시를 수정하여 개발자의 혼동을 줄였습니다.
버그 수정: 회원가입 시 기본 알림 설정 생성
- 신규 사용자가 회원가입(signUp, socialSignUp)을 완료하는 시점에 모든 채널의 알림 수신 동의가 true로 설정된 기본값을 자동으로 생성하도록 UserService를 수정했습니다.
- 이를 통해, 알림 설정 데이터가 없어 발생하던 조회 API의 잠재적 오류를 해결하고 데이터 정합성을 보장합니다.
API 문서 개선: 알림 설정 변경 API의 Swagger 예시 수정
- NotificationSettingsController의 PUT /api/v1/notification-settings/me API의 Swagger 문서에서 잘못된 Request body 예시(nickname)가 표시되던 문제를 해결했습니다.
- @ExampleObject 어노테이션을 사용하여, 실제 API 명세에 맞는 올바른 JSON 형식({ "type": "INTAKE", "channel": "PUSH", "isEnabled": false })의 예시를 명시적으로 제공하도록 수정했습니다.
=> fix(#160): 알림설정 로직 변경

src/main/java/com/vitacheck/controller/NotificationSettingsController.java
Close #162 
알림 기능의 안정성과 확장성을 개선하고 API 문서의 명확성을 높이기 위한 전반적인 리팩토링 및 버그 수정을 진행했습니다.
리팩토링: 알림 발송 스케줄러 방식 변경 (EC2 Cron Job 기반)
- 서버 부하를 줄이고 확장성을 확보하기 위해, NotificationScheduler의 @Scheduled 어노테이션을 제거했습니다.
- EC2 Cron Job이 호출할 수 있도록, 알림 발송을 트리거하는 내부 API 엔드포인트(POST /api/v1/notification-settings/internal/trigger-notifications)를 NotificationSettingsController에 새로 추가했습니다.
- 해당 API는 보안을 위해 서버 내부(localhost)요청만 허용하도록 구현했습니다.
알림 기능의 핵심 로직과 인프라 연동 방식에 대한 변경이 있었습니다. 특히 새로 추가된 내부 API의 보안 로직과 기존 스케줄러 제거 부분을 중점적으로 확인해주시면 감사하겠습니다. 이 변경으로 서버의 안정성과 확장성이 크게 개선될 것으로 기대합니다. 코드 리뷰 부탁드립니다! 😊
=> feat(#162): ec2 cron job 구현

src/main/java/com/vitacheck/controller/UserController.java, src/main/java/com/vitacheck/domain/user/User.java, src/main/java/com/vitacheck/dto/UserDto.java, src/main/java/com/vitacheck/service/NotificationSettingsService.java, src/main/java/com/vitacheck/service/UserService.java
Close #173 
사용자 피드백으로 접수된 두 가지 주요 사항을 해결했습니다. 알림 설정을 켰을 때 DB에 반영되지 않던 버그를 수정하고, 마이페이지 정보 수정 API의 기능을 확장하여 사용자 편의성을 개선했습니다.
1. 버그 수정: 알림 설정 변경이 DB에 반영되지 않는 문제 해결
- 문제 원인: NotificationSettingsService 클래스 전체에 @Transactional(readOnly = true)가 설정되어 있어, 데이터를 변경해야 하는 updateNotificationSetting 메소드까지 영향을 받아 변경 사항이 DB에 최종 커밋되지 않았습니다.
- 해결: updateNotificationSetting 메소드에 @Transactional 어노테이션을 개별적으로 추가하여, 해당 메소드는 정상적으로 쓰기 작업이 가능하도록 수정했습니다. 이로써 알림 설정을 켜는(true) 동작이 DB에 올바르게 반영됩니다.
---
2. 기능 확장: 마이페이지 정보 수정 기능 (생년월일, 연락처 추가)
기존에 닉네임만 수정 가능했던 마이페이지 정보 수정 API(PUT /api/v1/users/me)의 기능을 확장하여 생년월일과 휴대폰 번호도 함께 변경할 수 있도록 개선했습니다.
수정 내역:
- UserDto.UpdateRequest에 birthDate, phoneNumber 필드를 추가했습니다.
- User 엔티티에 여러 정보를 한 번에 업데이트하는 updateInfo 메소드를 추가했습니다.
- UserService가 확장된 DTO를 처리하도록 updateMyInfo 메소드의 로직을 수정했습니다.
=> feat(#173): 알림설정 저장 및 정보 업데이트 수정

src/main/java/com/vitacheck/controller/NotificationRoutineCustomRestController.java, src/main/java/com/vitacheck/domain/CustomSupplement.java, src/main/java/com/vitacheck/domain/notification/NotificationRoutine.java, src/main/java/com/vitacheck/dto/CustomRoutineUpsertRequestDto.java, src/main/java/com/vitacheck/dto/RoutineResponseDto.java, src/main/java/com/vitacheck/repository/CustomSupplementRepository.java, src/main/java/com/vitacheck/repository/NotificationRoutineRepository.java, src/main/java/com/vitacheck/service/NotificationRoutineCommandService.java, src/main/java/com/vitacheck/service/NotificationRoutineCustomCommandService.java, src/main/java/com/vitacheck/service/RoutineQueryService.java
Close #170 
사용자 정의(Custom) 영양제 복용 루틴 API 추가 및 수정
등록/수정 통합 API (POST /api/v1/notifications/routines/custom) 구현
notificationRoutineId 존재 시 → 수정
없을 시 → 신규 등록
@Transactional(readOnly = false) 적용하여 DB 쓰기 가능하도록 수정
삭제 API 구현 (DELETE /api/v1/notifications/routines/custom/{id})
현재 로그인 사용자 소유 여부 검증 후 삭제
조회 로직 보완
기존 getMyRoutines 조회 시 Custom 루틴도 포함되도록 수정
isTaken 필드 정상 반영 (IntakeRecord 기반)
커스텀 루틴 등록/수정 통합 처리
커스텀 루틴 삭제 기능 추가
루틴 목록 조회 시 커스텀 루틴 포함 및 isTaken 값 보완
@Transactional(readOnly = false) 적용으로 INSERT/UPDATE 정상 동작
기존 NotificationRoutine 로직과 최대한 동일하게 맞춰 구현했습니다.
=> feat(#170): 완료

src/main/java/com/vitacheck/config/SwaggerConfig.java, src/main/java/com/vitacheck/config/jwt/JwtUtil.java, src/main/java/com/vitacheck/config/oAuth/OAuth2SuccessHandler.java, src/main/java/com/vitacheck/controller/AuthController.java, src/main/java/com/vitacheck/dto/UserDto.java, src/main/java/com/vitacheck/service/UserService.java
Close #197 
신규 사용자의 소셜 로그인 시, 기존에 사용자 정보를 URL 쿼리 파라미터로 전달하던 방식의 보안 문제를 해결하고 전체적인 안정성을 개선했습니다.
Redis와 같은 외부 저장소 의존성 없이, 모든 소셔 프로필 정보를 암호화한 임시 JWT(tempToken)를 발급하여 프론트엔드와 안전하게 통신하는 Stateless 방식으로 회원가입 로직을 전면 수정했습니다. 또한, 이 과정에서 발생한 운영 환경의 ALB(로드밸런서) unhealthy 문제와 Swagger CORS 오류를 함께 해결하여 배포 안정성을 확보했습니다.
[x] 소셜 로그인 로직 변경 (Stateless JWT 도입)
- JwtUtil을 확장하여 소셜 프로필 정보 전체를 담는 임시 토큰 생성(createTempSocialToken) 및 추출(getSocialAttributesFromToken) 기능을 추가했습니다.
- OAuth2SuccessHandler가 신규 사용자 로그인 시, 위에서 생성한 임시 토큰을 URL 파라미터에 담아 프론트엔드로 리다이렉트하도록 수정했습니다.
- AuthController와 UserService가 최종 회원가입 시, Authorization 헤더의 임시 토큰과 RequestBody의 추가 정보를 조합하여 처리하도록 수정했습니다.
[x] ALB unhealthy 상태 및 504 오류 해결
- 로드밸런서의 상태 검사(Health Check) 전용 /health API 엔드포인트를 추가했습니다 (HealthCheckController).
- SecurityConfig에 /health 경로를 인증 없이 …
=> feat(#197): 임시 토큰 발급

src/main/java/com/vitacheck/config/SecurityConfig.java, src/main/java/com/vitacheck/controller/NotificationRoutineController.java, src/main/java/com/vitacheck/domain/RoutineDetail.java, src/main/java/com/vitacheck/domain/notification/NotificationRoutine.java, src/main/java/com/vitacheck/repository/IntakeRecordRepository.java, src/main/java/com/vitacheck/repository/NotificationRoutineRepository.java, src/main/java/com/vitacheck/service/NotificationRoutineCommandService.java
Close #199 
사용자가 각 복용 루틴의 알림을 개별적으로 켜고 끌 수 있는 토글 기능을 추가했습니다. 사용자는 더 이상 필요하지 않은 알림을 비활성화하여 개인화된 알림 경험을 가질 수 있습니다.
NotificationRoutineController 추가:
- PATCH /api/v1/notifications/routines/{notificationRoutineId}/toggle 엔드포인트를 추가하여 특정 루틴의 알림 상태를 변경합니다.
NotificationRoutineCommandService 수정:
- toggleRoutine 비즈니스 로직을 추가하여 루틴의 isEnabled 상태를 변경하고, 변경된 결과를 RoutineResponseDto로 반환합니다.
NotificationRoutine 엔티티 수정:
- isEnabled 필드의 상태를 간편하게 변경할 수 있도록 toggleEnabled() 편의 메소드를 추가했습니다.
IntakeRecordRepository 수정:
- 섭취 여부를 더 명확하게 조회하기 위해 existsByNotificationRoutineAndUserAndDateAndIsTaken 메서드를 추가했습니다.
=> feat(#199): NotificationRoutine 토글 기능 추가

src/main/java/com/vitacheck/config/SecurityConfig.java, src/main/java/com/vitacheck/controller/TermsController.java, src/main/java/com/vitacheck/dto/TermsDto.java, src/main/java/com/vitacheck/repository/TermsRepository.java, src/main/java/com/vitacheck/repository/UserTermsAgreementRepository.java, src/main/java/com/vitacheck/service/TermsService.java
Close #212 
회원가입 및 사용자 설정에 필요한 **약관 조회, 동의, 철회 기능**을 구현했습니다. 사용자가 약관 내용을 확인하고, 필수 및 선택 약관에 대해 동의 의사를 명확히 기록하며, 필요시 동의를 철회할 수 있는 시스템의 기반을 마련했습니다.
<br>
-   **`GET /api/v1/terms`**: DB에 저장된 모든 약관의 목록을 조회하는 API를 구현했습니다. `SecurityConfig`에 해당 경로를 `permitAll`로 설정하여 비로그인 사용자도 접근 가능합니다.
-   **`POST /api/v1/terms/agreements`**: 사용자가 **아직 동의하지 않은** 약관에 대해서만 신규 동의를 기록하는 API를 구현했습니다.
-   기존에 동의한 약관 ID가 요청에 포함되어도 중복으로 저장되지 않도록 방지 로직을 추가했습니다.
-   **`DELETE /api/v1/terms/agreements`**: 사용자가 기존에 동의했던 약관을 철회하는 API를 신규 구현했습니다.
-   **동의 시**: `TermsService`에서 사용자가 '마케팅 목적 개인정보 수집 동의' 약관에 동의하는 경우, `notification_settings` 테이블에서 해당 사용자의 `EVENT` 관련 알림 설정을 모두 `true`(활성화)로 자동 업데이트하도록 구현했습니다.
-   **철회 시**: 반대로 마케팅 약관 동의를 철회하면, 관련 알림 설정을 모두 `false`(비활성화)로 업데이트하도록 구현했습니다.
-   `Terms` (약관 원본), `UserTermsAgreement` …
=> feat(#212): 약관 수락 및 철회 기능 구현

src/main/java/com/vitacheck/controller/SupplementController.java, src/main/java/com/vitacheck/repository/SearchLogRepositoryCustom.java, src/main/java/com/vitacheck/repository/SearchLogRepositoryImpl.java, src/main/java/com/vitacheck/service/SupplementService.java
Close #243
📝 작업 내용
기존에 연령대별로만 조회가 가능했던 '인기 영양제 조회 API'에 성별 필터링 기능을 추가했습니다.
이제 ageGroup과 gender 파라미터를 조합하여 "20대 여성이 많이 찾는 영양제"와 같이 더 세분화된 통계 조회가 가능합니다.
✅ 변경 사항
[x] StatisticsController: gender 요청 파라미터 및 Swagger 명세 추가
[x] StatisticsService: findPopularSupplements 메소드에 gender 파라미터 전달 로직 추가
[x] SearchLogRepository: Querydsl을 사용하여 gender를 동적으로 필터링하는 WHERE 조건 추가
📷 스크린샷 (선택)
💬 리뷰어에게
=> feat(#243):인기 영양제 API 성별 필터링 추가

src/main/java/com/vitacheck/controller/IngredientController.java, src/main/java/com/vitacheck/controller/SearchController.java, src/main/java/com/vitacheck/controller/SupplementController.java, src/main/java/com/vitacheck/dto/SupplementDto.java, src/main/java/com/vitacheck/repository/BrandRepository.java, src/main/java/com/vitacheck/repository/IngredientRepository.java, src/main/java/com/vitacheck/repository/PurposeCategoryRepository.java, src/main/java/com/vitacheck/repository/SupplementRepository.java, src/main/java/com/vitacheck/service/SupplementService.java
Close #277 
통합 검색 로직을 수정하고, cursor 페이지 제너레이션 도입하여 속도를 개선함
페이지 제너레이션으로 인해, 여러번 검색 api가 호출되기 때문에, 검색 api와 검색 기록 api 를 따로 분리함
1. 검색 로직은 다음과 같이 변경하였습니다.
통합 검색 api → 성분 검색  api + 제품 검색 api +검색기록 api 로 분리
2. 제품 검색에는 아래의 경우의 수를 고려하였습니다.
1) 키워드로 매칭된 성분을 포함한 제품
2) 키워드로 매칭된 브랜드와 연관된 제품
3) 키워드를 제품 이름에 포함하여 매칭된 제품
- cursor ID는 인기도와 supplementId를 이용하여 만든 cursor용 ID입니다. (인기도 *1000000 + supplementId로 구성)
- 검색과 검색 기록 로직을 분리하였기 때문에, 검색할 때, /api/v1/search-logs 를 호출해주어야합니다. (성분 검색 예외 - 내부에 로직 있음)
=> [REFRACTOR#277] 통합 검색 로직 수정 + cursor 페이지 제너레이션 + 검색 기록

src/main/java/com/vitacheck/controller/SupplementController.java, src/main/java/com/vitacheck/service/IngredientService.java
Close #277 
성분 검색도 검색 api와 검색 기록 api를 분리하여 통일성을 확보함
검색하면 예외 없이 /api/v1/search-logs를 호출해주세요
=> [REFRACTOR#277] 성분 검색 api에서 검색 기록 로직 분리 #288

src/main/java/com/vitacheck/controller/NotificationSettingsController.java, src/main/java/com/vitacheck/service/NotificationSettingsService.java
Close #298 
내 알림 설정 변경 api 에서 알림이 켜지지않는 오류 수정
DB에서 사용자 설정이 변경되는것을 확인했습니다.
입력을 받으면 현재 상태를 반대로 (ex. 끄기 → 켜기, 켜기 → 끄기)로 동작하도록 로직을 변경하였기 때문에,   "isEnabled": true를 입력받지 않아도 됩니다. 추후 프론트와 isEnabled 값을 어떻게 할지 논의하겠습니다.
=> [BUG#298] 내 알림 설정 변경 api 오류 수정

src/main/java/com/vitacheck/controller/IngredientController.java
Close #303 
인기 검색 성분 조회 api url 수정(미로그인도 접근 가능)
→ 미로그인 시에도 접근 가능하도록, 이미 permit 되어있는 "/api/v1/ingredients/**"에 속하도록 url 변경함
=> [REFRACTOR] 인기 검색 성분 조회 api url 수정(미로그인도 접근 가능)

.github/workflows/ci.yml
배포 브랜치 변경 ( deploy → main)
기존 개발 과정에서 develop 을 배포 브랜치로 사용하였으나, 이후 출시를 목표로 디벨롭하기로 하여 main 브랜치를 배포 브랜치로 변경함.(Vitacheck version2)
=> [REFRACTOR#322] 배포 브랜치 변경 ( deploy → main)

module-auth/build.gradle, module-auth/src/main/java/com/vitacheck/auth/config/SecurityConfig.java, module-auth/src/main/java/com/vitacheck/auth/config/jwt/JwtUtil.java, module-auth/src/main/java/com/vitacheck/auth/config/oauth/OAuth2SuccessHandler.java, module-auth/src/main/java/com/vitacheck/auth/service/AuthService.java, module-user/build.gradle, module-user/src/main/java/com/vitacheck/user/controller/UserController.java, module-user/src/main/java/com/vitacheck/user/dto/AuthUserDto.java, module-user/src/main/java/com/vitacheck/user/dto/CreateUserRequest.java, module-user/src/main/java/com/vitacheck/user/service/AuthUserProviderImpl.java, module-user/src/main/java/com/vitacheck/user/service/UserRegistrationServiceImpl.java, module-user/src/main/java/com/vitacheck/user/service/provider/AuthUserProvider.java, module-user/src/main/java/com/vitacheck/user/service/provider/UserRegistrationService.java
Close #354 
AuthController에는 API 엔드포인트만 남기고 데이터 처리는 user 모듈에서 하도록 변경
추후 terms, notification 분리 고려해보겠습니다.
=> fix(#354): 회원가입 데이터 처리 user 모듈에서 진행하도록 변경
